name: flutter_next_auth_riverpod
description: Riverpod integration for NextAuth authentication in Flutter, providing reactive state management for session and authentication status.
version: 1.0.5
repository: https://github.com/jcyuan/flutter_next_auth_riverpod
issue_tracker: https://github.com/jcyuan/flutter_next_auth_riverpod/issues
homepage: https://github.com/jcyuan/flutter_next_auth_riverpod#readme
environment:
  sdk: ">=3.10.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  flutter_next_auth_core: ^1.0.5
  
  flutter_riverpod: ^3.1.0
